import { useMemo } from 'react';
import { StyleSheet } from 'react-native';
import { useTheme, spacing, radius, display as displayTokens } from '../../context/ThemeContext';

export function useCommunityStyles() {
  const { colors, isDark } = useTheme();
  const styles = useMemo(() => createStyles(colors, isDark), [colors, isDark]);
  return { styles, colors, isDark };
}

function createStyles(colors: { background: string; card: string; cardElevated?: string; text: string; muted: string; overlay: string; input: string; border: string; brand: string; accentSoft?: string }, isDark: boolean) {
  const display = { ...displayTokens, textTransform: 'uppercase' as const };
  const warmText = isDark ? '#FFB27A' : '#C2410C';
  const softOrange = isDark ? 'rgba(255,106,0,0.14)' : 'rgba(255,106,0,0.10)';
  const softBorder = isDark ? 'rgba(255,255,255,0.10)' : 'rgba(255,106,0,0.28)';
  // Flat editorial card with a hairline outline.
  const surface = isDark ? '#141414' : colors.card;
  const ink = isDark ? '#FFFFFF' : colors.text;
  const mutedInk = isDark ? '#C9C9C9' : colors.muted;
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: 'transparent' },
  scrollContainer: { flex: 1, backgroundColor: 'transparent' },
  scrollContent: { padding: spacing.section },
  list: { flex: 1, backgroundColor: 'transparent' },
  listContent: { paddingHorizontal: spacing.section, paddingTop: spacing.card, paddingBottom: 40, flexGrow: 1 },
  homeContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  heading: { ...display, fontSize: 32, marginBottom: 6, color: ink },
  subHeading: { fontSize: 15, color: mutedInk, marginBottom: 20 },
  sectionTitle: { ...display, fontSize: 20, marginTop: 28, marginBottom: 14, color: ink },
  backRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  backText: { color: colors.brand, fontSize: 15, fontWeight: '600', marginLeft: 4 },
  tagRow: { flexDirection: 'row', alignItems: 'center' },
  footerActionRow: { flexDirection: 'row', alignItems: 'center' },
  navButtonsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: spacing.card,
    gap: 10,
  },
  navButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: softOrange,
    borderColor: softBorder,
    borderWidth: 1,
    borderRadius: radius.pill,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  navButtonText: { color: colors.text, fontWeight: '700', fontSize: 13 },
  segmentBar: {
    flexDirection: 'row',
    backgroundColor: surface,
    borderRadius: radius.image,
    borderWidth: 1,
    borderColor: softBorder,
    padding: 4,
    marginBottom: 14,
    gap: 4,
  },
  segmentBtn: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 12,
  },
  segmentBtnOn: { backgroundColor: colors.brand },
  segmentBtnText: { fontSize: 12, fontWeight: '800', color: colors.text },
  segmentBtnTextOn: { color: '#FFFFFF' },
  gymPillRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  gymPill: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: softBorder,
    backgroundColor: softOrange,
    paddingVertical: 10,
    paddingHorizontal: 6,
    alignItems: 'center',
  },
  gymPillOn: { borderColor: colors.brand, backgroundColor: softOrange },
  gymPillCode: { fontSize: 12, fontWeight: '800', color: colors.text },
  gymPillStatus: { fontSize: 10, fontWeight: '700', marginTop: 2 },
  moreCompose: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 8,
  },
  moreComposeText: { fontSize: 12, fontWeight: '700', color: colors.muted },
  mainButton: {
    backgroundColor: colors.brand,
    borderRadius: radius.pill,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  submitButton: { marginTop: spacing.section, marginBottom: 40 },
  mainButtonText: { color: '#fff', fontWeight: '600', fontSize: 16 },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.input,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginRight: 8,
    backgroundColor: colors.input,
    color: colors.text,
  },
  profileInput: {
    fontSize: 16,
    paddingVertical: 12,
    marginBottom: 20,
    marginRight: 0,
  },
  fieldLabel: { fontSize: 14, fontWeight: '600', color: colors.muted, marginBottom: 6 },
  avatarSection: { alignItems: 'center', marginBottom: 24 },
  avatarPlaceholder: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: isDark ? '#222222' : '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: isDark ? '#333333' : '#d1d5db',
    overflow: 'hidden',
  },
  iconPlaceholderWrap: { alignItems: 'center', justifyContent: 'center' },
  avatarPlaceholderText: { color: colors.muted, fontWeight: '500', fontSize: 12, marginTop: 4 },
  avatarImage: { width: '100%', height: '100%' },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 12 },
  chip: {
    borderWidth: 1,
    borderColor: isDark ? colors.border : '#d1d5db',
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 8,
    marginBottom: 8,
    backgroundColor: colors.overlay,
  },
  chipSelected: {
    borderColor: colors.brand,
    backgroundColor: softOrange,
  },
  chipText: { color: colors.text, fontSize: 13, fontWeight: '500' },
  chipTextSelected: { color: colors.brand, fontWeight: '600' },
  profileBadgeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.overlay,
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: isDark ? colors.border : '#e5e7eb',
  },
  bannerAvatar: { width: 44, height: 44, borderRadius: 22, marginRight: 12 },
  bannerWelcome: { fontSize: 14, fontWeight: '600', color: colors.text },
  bannerCampusSub: { fontSize: 12, color: colors.muted, marginTop: 2 },

  // Gym Busyness Styles
  meterContainer: {
    backgroundColor: surface,
    borderRadius: 12,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: isDark ? colors.border : '#e2e8f0',
  },
  meterTitleRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  meterTitle: { fontSize: 16, fontWeight: '700', color: ink },
  meterCampusRow: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  meterCard: {
    flex: 1,
    backgroundColor: isDark ? '#0C0C0C' : colors.input,
    borderRadius: radius.input,
    padding: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: isDark ? colors.border : '#cbd5e1',
  },
  meterCardSelected: { borderColor: colors.brand, backgroundColor: softOrange, borderWidth: 2 },
  meterCampusText: { fontSize: 13, fontWeight: '700', color: ink },
  meterBadgeText: { fontSize: 12, fontWeight: '700', marginTop: 2 },
  meterTimeText: { fontSize: 10, color: colors.muted, marginTop: 2 },
  toggleCampusesBtn: {
    alignSelf: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  toggleCampusesText: { color: colors.brand, fontWeight: '600', fontSize: 13 },
  noteRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  meterNote: { fontSize: 12, fontStyle: 'italic', color: isDark ? '#D4D4D4' : '#334155', flex: 1 },
  checkInBox: {
    backgroundColor: isDark ? '#0C0C0C' : colors.input,
    borderRadius: radius.input,
    padding: 10,
    borderWidth: 1,
    borderColor: isDark ? colors.border : '#e2e8f0',
  },
  checkInLabel: { fontSize: 12, fontWeight: '600', color: isDark ? '#9A9A9A' : '#475569', marginBottom: 8 },
  busynessBtnRow: { flexDirection: 'row', gap: 6 },
  statusBtn: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 8,
    borderRadius: 6,
    alignItems: 'center',
  },
  btnQuiet: { backgroundColor: isDark ? 'rgba(255,178,122,0.18)' : 'rgba(255,106,0,0.08)' },
  btnModerate: { backgroundColor: isDark ? 'rgba(255,106,0,0.28)' : 'rgba(255,106,0,0.16)' },
  btnPacked: { backgroundColor: isDark ? 'rgba(194,65,12,0.35)' : 'rgba(194,65,12,0.14)' },
  statusBtnText: { fontSize: 12, fontWeight: '700', color: isDark ? ink : '#1f2937' },

  // Shared Workout Log Styles
  workoutTriggerButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: colors.brand,
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 12,
  },
  workoutTriggerText: { color: '#FFFFFF', fontWeight: '800', fontSize: 14, letterSpacing: 0.8, textTransform: 'uppercase' },
  recipeTriggerButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: softOrange,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: softBorder,
    paddingVertical: 13,
    alignItems: 'center',
    marginBottom: 12,
  },
  recipeTriggerText: { color: colors.text, fontWeight: '700', fontSize: 14 },
  recipeTag: { fontSize: 11, color: warmText, fontWeight: '600' },
  recipeCardBadge: {
    backgroundColor: softOrange,
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: softBorder,
  },
  recipeCardTitle: { fontSize: 16, fontWeight: '800', color: warmText },
  recipeCardGoal: { fontSize: 12, fontWeight: '700', color: colors.brand, marginBottom: 8 },
  recipeSubHead: { marginTop: 8, marginBottom: 4, fontSize: 12, fontWeight: '800', color: colors.text },
  recipeLine: { fontSize: 13, lineHeight: 19, color: colors.text, marginBottom: 2 },
  workoutCardBadge: {
    backgroundColor: softOrange,
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: softBorder,
  },
  workoutCardTitle: { fontSize: 15, fontWeight: '700', color: warmText },
  workoutStatsRow: { flexDirection: 'row', gap: 8 },
  statChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.input,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: isDark ? colors.border : '#FFEDD5',
  },
  statChipLabel: { fontSize: 10, color: colors.muted },
  statChipVal: { fontSize: 12, fontWeight: '700', color: colors.text },

  // Challenge Styles
  challengeDesc: { fontSize: 13, color: colors.muted, marginTop: 4, marginBottom: 8 },
  leaderboardBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDark ? colors.overlay : '#fef3c7',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    marginBottom: 10,
  },
  leaderboardBadgeText: { fontSize: 12, color: warmText },
  viewPlanBtn: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6 },
  viewPlanBtnText: { color: colors.brand, fontWeight: '600', fontSize: 13 },
  tabContainer: { flexDirection: 'row', gap: 8, marginBottom: 14 },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: radius.input,
    backgroundColor: colors.overlay,
  },
  tabActive: { backgroundColor: colors.brand },
  tabText: { fontSize: 13, fontWeight: '600', color: colors.muted },
  tabTextActive: { color: '#fff' },
  leaderboardBox: { backgroundColor: isDark ? colors.overlay : '#f9fafb', padding: 12, borderRadius: radius.input, marginBottom: 12 },
  leaderboardRow: { marginBottom: 10 },
  leaderboardHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  campusRankText: { fontWeight: '700', fontSize: 13, color: colors.text },
  campusScoreText: { fontSize: 12, color: colors.muted },
  barBackground: { height: 10, backgroundColor: isDark ? colors.border : '#e5e7eb', borderRadius: 5, overflow: 'hidden' },
  barFill: { height: '100%', backgroundColor: colors.brand },

  // Modal Styles
  modalOverlay: {
    flex: 1,
    minHeight: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: colors.input,
    borderRadius: 12,
    padding: 20,
    flexGrow: 1,
  },
  photoUploadButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: isDark ? colors.border : '#cbd5e1',
    borderStyle: 'dashed',
    borderRadius: radius.input,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 12,
    backgroundColor: colors.overlay,
  },
  photoUploadText: { color: colors.brand, fontWeight: '600', fontSize: 14 },
  modalImagePreview: { width: '100%', height: 160, borderRadius: radius.image },
  modalButtonRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 10 },
  modalCancelBtn: { paddingVertical: 12, paddingHorizontal: 16, justifyContent: 'center' },
  modalCancelText: { color: colors.muted, fontWeight: '600' },

  composeGlass: {
    backgroundColor: isDark ? '#141414' : colors.overlay,
    borderRadius: radius.card,
    padding: 14,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255,255,255,0.10)' : colors.border,
  },
  postButton: {
    backgroundColor: colors.brand,
    borderRadius: 999,
    paddingHorizontal: 18,
    justifyContent: 'center',
    paddingVertical: 10,
  },
  postButtonText: { color: '#fff', fontWeight: '800', letterSpacing: 0.4 },
  captionInput: {
    marginBottom: 10,
    minHeight: 48,
    textAlignVertical: 'top',
    marginRight: 0,
    borderRadius: 6,
    borderWidth: 0,
    backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : colors.input,
  },
  postActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
    marginBottom: 0,
  },
  photoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0,
    backgroundColor: softOrange,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  photoButtonText: { color: colors.text, fontWeight: '700', fontSize: 12 },
  imagePreviewWrap: { marginBottom: 8, position: 'relative', alignSelf: 'flex-start' },
  imagePreview: { width: 120, height: 120, borderRadius: radius.image },
  removeImageButton: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#111827',
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    backgroundColor: surface,
    borderRadius: radius.card,
    padding: isDark ? 16 : 14,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: softBorder,
  },
  checkInPostCard: {
    backgroundColor: surface,
    borderWidth: 1,
    borderColor: softBorder,
  },
  checkInTag: { fontSize: 11, color: colors.brand, fontWeight: '700' },
  mediaCard: {
    backgroundColor: colors.overlay,
    borderRadius: radius.input,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: isDark ? colors.border : '#e5e7eb',
    marginBottom: 12,
  },
  cardImage: { width: '100%', height: 140 },
  cardBody: { padding: 12 },
  postHeaderRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  postAvatar: { width: 32, height: 32, borderRadius: 16, marginRight: 8 },
  postAvatarFallback: { backgroundColor: isDark ? colors.border : '#d1d5db', alignItems: 'center', justifyContent: 'center' },
  fallbackAvatarText: { fontWeight: 'bold', color: isDark ? ink : '#4b5563', fontSize: 14 },
  author: {
    fontFamily: 'Anton_400Regular',
    fontSize: 16,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: ink,
  },
  postImage: { width: '100%', height: 240, borderRadius: 6, marginBottom: 10 },
  postText: { marginBottom: 8, color: ink, lineHeight: 21 },
  postFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  darkFooterLeft: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  darkTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
  darkBrandRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  darkAvatar: { width: 36, height: 36, borderRadius: 18 },
  darkAvatarFallback: { backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center' },
  darkAvatarLetter: { color: '#594338', fontWeight: '700' },
  darkBrand: { color: colors.brand, fontSize: 22, fontWeight: '700' },
  darkSearchRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 18 },
  darkSearch: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: surface,
    borderRadius: radius.input,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    height: 46,
  },
  darkSearchInput: { flex: 1, color: ink, fontSize: 15 },
  darkPlus: {
    width: 46,
    height: 46,
    borderRadius: radius.input,
    backgroundColor: colors.brand,
    alignItems: 'center',
    justifyContent: 'center',
  },
  darkCompose: { marginBottom: 12 },
  darkSectionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  darkSectionTitle: { ...display, color: ink, fontSize: 18 },
  darkViewAll: { color: colors.brand, fontWeight: '600', fontSize: 13 },
  darkActiveRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  darkActiveCard: {
    flex: 1,
    backgroundColor: surface,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
  },
  darkKicker: { color: colors.muted, fontSize: 11, fontWeight: '700', letterSpacing: 0.6, marginBottom: 6 },
  darkActiveName: { color: ink, fontSize: 15, fontWeight: '700', marginBottom: 4 },
  darkActiveMeta: { color: '#9A9A9A', fontSize: 12, marginBottom: 10 },
  darkJoin: { color: colors.brand, fontWeight: '700', fontSize: 13 },
  darkMeta: { color: '#9A9A9A', fontSize: 12, marginTop: 2 },
  darkTagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 10 },
  darkTag: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  darkTagText: { color: colors.text, fontSize: 12 },
  likeText: { color: colors.brand, fontWeight: '500' },
  commentBtnText: { color: isDark ? ink : colors.muted, fontWeight: '500' },
  commentsContainer: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: isDark ? colors.border : '#e5e7eb',
  },
  commentBubble: {
    backgroundColor: colors.input,
    padding: 8,
    borderRadius: 6,
    marginBottom: 6,
  },
  commentAuthor: { fontWeight: '600', fontSize: 12, color: colors.muted },
  commentText: { fontSize: 13, color: colors.text, marginTop: 2 },
  commentInputRow: {
    flexDirection: 'row',
    marginTop: 6,
  },
  rowCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rowTextBold: { fontSize: 16, fontWeight: '600', flexShrink: 1, marginRight: 8, color: colors.text },
  campusBadge: { fontSize: 12, color: colors.muted },
  linkSubtext: { fontSize: 12, color: colors.muted, marginTop: 4 },
  linkText: { color: colors.brand },
  smallButton: {
    backgroundColor: colors.brand,
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  joinedButton: { backgroundColor: '#9ca3af' },
  smallButtonText: { color: '#fff', fontWeight: '600', fontSize: 13 },
  createBox: {
    backgroundColor: colors.overlay,
    padding: 12,
    borderRadius: radius.input,
    marginVertical: 8,
  },
  smallPreviewImage: { width: 80, height: 80, borderRadius: 6, marginBottom: 8 },
  progressText: { color: colors.muted, marginBottom: 12, fontSize: 14 },
  dayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: colors.overlay,
    borderRadius: radius.input,
    marginBottom: 6,
  },
  dayRowRest: { backgroundColor: isDark ? '#1F1F1F' : '#e5e7eb', opacity: 0.7 },
  dayRowDone: { backgroundColor: isDark ? 'rgba(74,222,128,0.18)' : '#dcfce7' },
  dayNumber: { fontWeight: '600', width: 60, color: colors.text },
  dayLabel: { flex: 1, color: colors.text },
  dayLabelRest: { fontStyle: 'italic', color: colors.muted },
});
}
